### ISSUE TITLE
Tests are strangely broken

### ISSUE THREAD

**Issue by pierrewillenbrockdfki** [rock-core/tools-orogen#12]
`rake test` only runs the rubocop compliance test when rubocup is available, but runs all test cases (except for gen) if rubocop is not available. `rake test:all` only adds the tests covered by `rake test:gen`, but still does not run the normal test cases when rubocop is available.

Also, at the moment, spec/test_project.rb fails because there is no check if the project name equals a task name. Either that check needs to be added back(like Gen::RTT_CPP::Project.task_context has), or the test removed.

@doudou i think you might have an idea how to correct this.

**Comment by doudou** [comment]
Right. So.

The spec tests in orogen should pass. I'll try to have a look.

The gen tests are deprecated (I left them here ... because I did not remote them). We now have a 'rock regression suite' in which I write new orogen tests. The goal of that separate suite was to be able to use autoproj for codegen and compilation, which speeds things up quite a bit. I would suggest you create yourself a repo with a test case of requiring a specific C++ standard and using some of its features in a loaded header.

To get the suite, bootstrap https://github.com/rock-core/rock.build-tests-buildconf

Example test package: https://github.com/rock-core/build_tests-orogen-using_task_library_not_picking_up_not_directly_used_dependencies_publisher

**Comment by pierrewillenbrockdfki** [comment]
> The gen tests are deprecated (I left them here ... because I did not remote them). We now have a 'rock regression suite' in which I write new orogen tests. The goal of that separate suite was to be able to use autoproj for codegen and compilation, which speeds things up quite a bit. I would suggest you create yourself a repo with a test case of requiring a specific C++ standard and using some of its features in a loaded header.
> 

Thank you, i did not know about that. It does have a bit of a problem when doing a fresh bootstrap: the extconf.rb of build_tests-autoproj-gem_build_flags(?) wants to see --with-package_set-init=success, but that fails to appear on its command line. After spamming that basically everywhere i could find with-package_set-packages, i got everything to build. Looks like the package-set in the buildconf does not have its init.rb called or the setting from there is overriden by the packages.autobuild or something like that. Keeps aup from completing.
